name: perbasitlg
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_svg: ^0.19.1
  flutter_bloc: ^6.0.1
  equatable: ^1.2.4
  dio: 3.0.9
  shared_preferences: any
  fluttertoast: ^7.1.1
  cached_network_image: ^2.3.3
  qr_flutter: ^3.1.0
  flutter_stetho:
    git:
      url: git://github.com/jasonlewicki/flutter_stetho.git
      ref: master
  flutter_screenutil: ^3.1.0
  flutter_html: ^1.1.1
  image_picker: ^0.6.7+14
  network_to_file_image: ^2.3.6
  path_provider: ^1.4.4
  url_launcher: ^5.7.10
  expandable: ^4.1.4
  firebase_messaging: ^7.0.3
  firebase_core : ^0.5.3
  flutter_uploader: ^1.2.1
  photo_view: ^0.10.3
  qr_code_scanner: ^0.3.2
  image: ^2.1.4
  overlay_support: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Thin.ttf